import "./globals.css";

import { Inter, Press_Start_2P } from "next/font/google";

const pressStart = Press_Start_2P({
  weight: "400",
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Memory Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={pressStart.className}>{children}</body>
    </html>
  );
}
